# Site wide configuration

title: So Simple Theme
locale: en_US
description: A simple and clean responsive Jekyll theme for words and photos.
logo: site-logo.png
search: true
url: //wangmingzhong.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ryan
  avatar: michael-rose-photo.jpg
  email: ipaler@ipaler.com
  disqus-shortname: ipaler
  twitter: wangmingzhong
  facebook: wangmingzhong
  github: ipaler
  stackexchange:
  linkedin:
  instagram: ipaler
  flickr:
  tumblr: ipaler
  google:
    plus: RyanDesign
    analytics: UA-2011187-2
    verify: UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8
    ad-client: ca-pub-7328585512091257
    ad-slot: 7855747535
  bing-verify: D81F4C18A6CB3018F64D7C827D953DFD